apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app 
    spec:
      containers:
      - name: node-app
        image: #path to your docker image
        ports:
        - containerPort: 8080