version: '3'

services:
  jaeger:
    container_name: 'jaeger'
    image: 'jaegertracing/all-in-one:latest'  
    ports:
      - "4318:4318"
      - "5775:5775/udp" 
      - "6831:6831/udp" 
      - "6832:6832/udp" 
      - "5778:5778" 
      - "16686:16686" 
      - "14268:14268" 
      - "9411:9411" 
    networks:
      - clcnet
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

  rating:
    container_name: 'rating'
    image: 'mich039/rating:latest'  
    ports:
      - "6789:6789"
    networks:
      - clcnet

  payment:
    container_name: 'payment'
    image: 'mich039/payment:latest'  
    ports:
      - "7777:7777"
    networks:
      - clcnet
    environment:
    - OTEL_TRACE_HOST=jaeger

  user:
    container_name: 'user'
    image: 'mich039/user:latest'  
    ports:
      - "8888:8888"
    networks:
      - clcnet
    environment:
    - OTEL_TRACE_HOST=jaeger



networks:
  clcnet:
volumes:
  redisVolume:
